"""Typed data contracts for the SAGE Connect API."""

from sage_mcp.types.auth import SageAuth
from sage_mcp.types.common import (
    CategoryListType,
    ImageSize,
    ProductEntityId,
    SageProductCode,
    SearchSortOrder,
    SupplierId,
)
from sage_mcp.types.errors import SageAPIError, SageErrorCode
from sage_mcp.types.requests import (
    CategoryListTypeName,
    CategoryRequest,
    InventoryProductRef,
    InventoryRequest,
    ProductDetailRequest,
    SearchProductsRequest,
    SearchRec,
    SearchSort,
)
from sage_mcp.types.responses import (
    CategoriesResponse,
    CategoryItem,
    InventoryProduct,
    InventoryResponse,
    OptionValue,
    ProductDetail,
    ProductDetailResponse,
    ProductImage,
    ProductOption,
    ProductSearchHit,
    SearchResponse,
    SkuAttribute,
    SkuRecord,
    SupplierInfo,
)

__all__ = [
    "CategoriesResponse",
    "CategoryItem",
    "CategoryListType",
    "CategoryListTypeName",
    "CategoryRequest",
    "ImageSize",
    "InventoryProduct",
    "InventoryProductRef",
    "InventoryRequest",
    "InventoryResponse",
    "OptionValue",
    "ProductDetail",
    "ProductDetailRequest",
    "ProductDetailResponse",
    "ProductEntityId",
    "ProductImage",
    "ProductOption",
    "ProductSearchHit",
    "SageAPIError",
    "SageAuth",
    "SageErrorCode",
    "SageProductCode",
    "SearchProductsRequest",
    "SearchRec",
    "SearchResponse",
    "SearchSort",
    "SearchSortOrder",
    "SkuAttribute",
    "SkuRecord",
    "SupplierId",
    "SupplierInfo",
]
